//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Ichigo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project_Ichigo.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/839905621377286184/Crit.png.
        /// </summary>
        internal static string CriticalLogIconUrl {
            get {
                return ResourceManager.GetString("CriticalLogIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/839854418861359114/Debug.png.
        /// </summary>
        internal static string DebugLogIconUrl {
            get {
                return ResourceManager.GetString("DebugLogIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/839843996779675648/Error.png.
        /// </summary>
        internal static string ErrorLogIconUrl {
            get {
                return ResourceManager.GetString("ErrorLogIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/893958382896173096/Github.png.
        /// </summary>
        internal static string GithubIconUrl {
            get {
                return ResourceManager.GetString("GithubIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/846833791079415878/GuildUpdated.png.
        /// </summary>
        internal static string GuildUpdatedIconUrl {
            get {
                return ResourceManager.GetString("GuildUpdatedIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/848916448147669033/Info.png.
        /// </summary>
        internal static string InfoBlueLogIconUrl {
            get {
                return ResourceManager.GetString("InfoBlueLogIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/890237551221284945/Info.png.
        /// </summary>
        internal static string InfoLogIconUrl {
            get {
                return ResourceManager.GetString("InfoLogIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/840588396660260904/Untitled.gif.
        /// </summary>
        internal static string LoadingGifUrlBlue {
            get {
                return ResourceManager.GetString("LoadingGifUrlBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/840601332225146890/Untitled_1.gif.
        /// </summary>
        internal static string LoadingGifUrlRed {
            get {
                return ResourceManager.GetString("LoadingGifUrlRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/839566709903720518/MessageRemoved.png.
        /// </summary>
        internal static string MessageDeletedIconUrl {
            get {
                return ResourceManager.GetString("MessageDeletedIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/839566700328517703/MessageUpdated.png.
        /// </summary>
        internal static string MessageEditedIconUrl {
            get {
                return ResourceManager.GetString("MessageEditedIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/899051918037504040/QuestionMark.png.
        /// </summary>
        internal static string QuestionMarkIconUrl {
            get {
                return ResourceManager.GetString("QuestionMarkIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/839566702190526514/UserAdded.png.
        /// </summary>
        internal static string UserAddedIconUrl {
            get {
                return ResourceManager.GetString("UserAddedIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/839911327056527380/UserBanned.png.
        /// </summary>
        internal static string UserBannedIconUrl {
            get {
                return ResourceManager.GetString("UserBannedIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/846830397220323328/BanRemoved.png.
        /// </summary>
        internal static string UserBanRemovedIconUrl {
            get {
                return ResourceManager.GetString("UserBanRemovedIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/839911329229176842/UserKicked.png.
        /// </summary>
        internal static string UserKickedIconUrl {
            get {
                return ResourceManager.GetString("UserKickedIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/839566703477260348/UserRemoved.png.
        /// </summary>
        internal static string UserLeftIconUrl {
            get {
                return ResourceManager.GetString("UserLeftIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/839566706032640088/UserUpdated.png.
        /// </summary>
        internal static string UserUpdatedIconUrl {
            get {
                return ResourceManager.GetString("UserUpdatedIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/839911324774301726/UserWarned.png.
        /// </summary>
        internal static string UserWarnedIconUrl {
            get {
                return ResourceManager.GetString("UserWarnedIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/712761268393738301/839843994850033664/Warning.png.
        /// </summary>
        internal static string WarningLogIconUrl {
            get {
                return ResourceManager.GetString("WarningLogIconUrl", resourceCulture);
            }
        }
    }
}
