#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

# This example catches duplicate Signed-off-by lines.

test "" = "$(grep '^Signed-off-by: ' "$1" |
	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
	echo "Duplicate Signed-off-by lines." >&2
	exit 1
}

if ! head -1 "$1" | grep -qE "^(Merge branch .*)|((feat|fix|ci|chore|docs|test|style|refactor|revert|perf)(\(.+?\))?!?: .{1,})$"; then
    echo "Your commit message is invalid. It must contain any of these prefixes:feat, fix, ci, chore, docs, test, style, refactor, perf or revert. You can suffix a ! to signal a breaking change and/or define the scope of the commit via (scope)." >&2
    exit 1
fi

if ! head -1 "$1" | grep -qE "^(Merge branch .*)|(.{1,50})$"; then
    echo "Your commit message is too long." >&2
    exit 1
fi
