name: Add new issue to project
on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: self-hosted
    steps:
      - name: Add new issue to column
        # You may pin to the exact commit or the version.
        # uses: konradpabjan/actions-add-new-issue-to-column@7a9ee8bfa125bf97c2fcfbac20ae8f82657f83ba
        uses: konradpabjan/actions-add-new-issue-to-column@v1.1
        with:
          # Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}
          action-token: "${{ secrets.Access_token }}"
          # The url of the project
          project-url: "https://github.com/TheXorog/Project-Ichigo/projects/2"
          # The column that the card should end up
          column-name: "To do"
