name: Build and Push to Production
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  push:
    name: Build Project
    runs-on: self-hosted
    steps:
      - name: Cleanup before build
        run: rm -rf ProjectIchigo/
      - name: Setup .NET Core SDK 6.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
      - name: "Clone Repository"
        uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
        working-directory: ProjectIchigo/ProjectIchigo/
      - name: Build Ichigo
        run: dotnet publish --configuration RELEASE --runtime linux-x64 --no-self-contained --output "/home/github-runner/build/"
        working-directory: ProjectIchigo/ProjectIchigo/
      - name: Writing current version to file
        run: git rev-parse --short HEAD > "/home/github-runner/build/LatestGitPush.cfg" && git branch --show-current >> /home/github-runner/build/LatestGitPush.cfg && echo $(date +%d.%m.%y) >> /home/github-runner/build/LatestGitPush.cfg && echo $(date +%H:%M:%S,00) >> /home/github-runner/build/LatestGitPush.cfg
        working-directory: ProjectIchigo/
      - name: Cleanup
        run: rm -rf ProjectIchigo/
      - name: Deleting old successful build
        run: rm -rf /home/github-runner/successful_build
      - name: Moving successful build
        run: mv /home/github-runner/build/ /home/github-runner/successful_build
      - name: Adjusting permissions for successful build
        run: chmod -R 0755 /home/github-runner/successful_build
