name: Start Build on Server
on:
  push:
    branches: [ main ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY_ED25519 }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        script: ${{ secrets.SSH_CMDLINE }}
