name: Build and Push to Production
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  push:
    name: Build Project
    runs-on: self-hosted
    steps:
      - name: Cleanup
        run: rm -rf ProjectIchigo/ Xorog.Logger/ Xorog.ScoreSaber/ Xorog.UniversalExtensions/
      - name: Setup .NET Core SDK 6.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
      - name: "Clone Repository"
        uses: actions/checkout@v3
        with:
          path: ProjectIchigo
      - name: "Clone Xorog.Logger"
        uses: actions/checkout@v3
        with:
          repository: Fortunevale/Xorog.Logger
          path: Xorog.Logger
      - name: "Clone Xorog.UniversalExtensions"
        uses: actions/checkout@v3
        with:
          repository: Fortunevale/Xorog.UniversalExtensions
          path: Xorog.UniversalExtensions
      - name: "Clone Xorog.ScoreSaber"
        uses: actions/checkout@v3
        with:
          repository: Fortunevale/Xorog.ScoreSaber
          path: Xorog.UniversalExtensions
          token: ${{ secrets.Access_token }}
      - run: pwd
      - run: cd ProjectIchigo
      - name: Install dependencies
        run: dotnet restore
      - name: Build Ichigo
        run: dotnet publish --configuration RELEASE --runtime linux-x64 --no-self-contained --output "/home/github-runner/build/"
      - name: Writing current version to file
        run: git rev-parse --short HEAD > "/home/github-runner/build/LatestGitPush.cfg" && git branch --show-current >> /home/github-runner/build/LatestGitPush.cfg && echo $(date +%d.%m.%y) >> /home/github-runner/build/LatestGitPush.cfg && echo $(date +%H:%M:%S,00) >> /home/github-runner/build/LatestGitPush.cfg
      - name: Cleanup
        run: rm -rf ProjectIchigo/ Xorog.Logger/ Xorog.ScoreSaber/ Xorog.UniversalExtensions/
      - name: Moving successful build
        run: mv /home/github-runner/build/ /home/github-runner/successful_build
