name: Test Dev Branch
on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:
  pull_request:
jobs:
  secretscan:
    name: Scan for Secrets
    runs-on: self-hosted
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - name: Secret Scan
      uses: max/secret-scan@master
      with:
        exclude_path: 'SecretsIgnore.txt'
  spellcheck:
    name: Spell Check with Typos
    runs-on: self-hosted
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - name: Check spelling
      uses: crate-ci/typos@master
  build:
    name: Build Project
    runs-on: self-hosted
    steps:
      - name: Cleanup before build
        run: rm -rf ProjectMakotoTest/
      - name: Setup .NET Core SDK 7.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - name: "Clone Repository"
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: ProjectMakotoTest
          token: ${{ secrets.Access_token }}
      - name: Remove TranslationSourceGenerator from Build
        run: dotnet sln remove ../TranslationSourceGenerator/TranslationSourceGenerator.csproj
        working-directory: ProjectMakotoTest/ProjectMakoto/
      - name: Install dependencies
        run: dotnet restore
        working-directory: ProjectMakotoTest/ProjectMakoto/
      - name: Test Build Makoto
        run: dotnet publish --configuration RELEASE --runtime linux-x64 --no-self-contained --framework net7.0 -v n
        working-directory: ProjectMakotoTest/ProjectMakoto/
        timeout-minutes: 5
