name: Deploy to Production Server
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    name: Build Project
    runs-on: self-hosted
    steps:
      - name: Cleanup before build
        run: rm -rf ProjectMakoto/
      - name: Setup .NET Core SDK 6.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
      - name: "Clone Repository"
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: ProjectMakoto
          token: ${{ secrets.Access_token }}
      - name: Install dependencies
        run: dotnet restore
        working-directory: ProjectMakoto/ProjectMakoto/
      - name: Build Makoto
        run: dotnet publish --configuration RELEASE --runtime linux-x64 --no-self-contained --output "build"
        working-directory: ProjectMakoto/ProjectMakoto/
      - name: Writing current version to file
        run: git rev-parse --short HEAD > "ProjectMakoto/build/LatestGitPush.cfg" && git branch --show-current >> ProjectMakoto/build/LatestGitPush.cfg && echo $(date +%d.%m.%y) >> ProjectMakoto/build/LatestGitPush.cfg && echo $(date +%H:%M:%S,00) >> ProjectMakoto/build/LatestGitPush.cfg
        working-directory: ProjectMakoto/
  deploy:
    name: Deploy Build to Server
    needs: build
    runs-on: self-hosted
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_TOKEN }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOST }}
      - name: Creating .ssh/ Folder
        run: mkdir ~/.ssh
      - name: Deploy with rsync
        run: rsync -avzn --delete --force -e "ssh -p ${{ secrets.SSH_PORT }}" . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER }}:/home/xorog/Bots/latestProjectIchigo/
        working-directory: build/
  cleanup:
    name: Cleanup
    needs: [ "build", "deploy" ]
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Cleanup Source Code
        run: rm -rf ProjectMakoto/
      - name: Cleanup Build
        run: rm -rf build/
