name: Secrets
on: ["push", "workflow_dispatch", "pull_request"]

jobs:
  run:
    name: Scan for Secrets
    runs-on: self-hosted
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v3

    - name: Secret Scan
      uses: max/secret-scan@master
