name: Spellcheck
on: [pull_request]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: self-hosted
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: Check spelling of file.txt
      uses: crate-ci/typos@master
