name: Spellcheck
on: ["push", "workflow_dispatch", "pull_request"]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: self-hosted
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v3

    - name: Check spelling
      uses: crate-ci/typos@master
